### ISSUE TITLE
Requirements could not be resolved using Drupal 9

### ISSUE THREAD

**Issue by robertoperuzzo** [lucacracco/robo-drupal#1]
Problem 1
    - lucacracco/robo-drupal dev-master requires heydon/robo-twig dev-master -> satisfiable by heydon/robo-twig[dev-master].
    - Installation request for lucacracco/robo-drupal dev-master -> satisfiable by lucacracco/robo-drupal[dev-master].
    - Conclusion: remove twig/twig v2.12.5
    - Conclusion: don't install twig/twig v2.12.5
    - heydon/robo-twig dev-master requires twig/twig ^1.35.0 -> satisfiable by twig/twig[1.x-dev, v1.35.0, v1.35.1, v1.35.2, v1.35.3, v1.35.4, v1.36.0, v1.37.0, v1.37.1, v1.38.0, v1.38.1, v1.38.2, v1.38.3, v1.38.4, v1.39.0, v1.39.1, v1.40.0, v1.40.1, v1.41.0, v1.42.0, v1.42.1, v1.42.2, v1.42.3, v1.42.4, v1.42.5, v1.43.0, v1.43.1, v1.44.0, v1.44.1, v1.44.2].

**Comment by lucacracco** [comment]
try 2.1.0 for Drupal ~9.0!

**Comment by robertoperuzzo** [comment]
2.1.0 works
