### ISSUE TITLE
Make settings.php and services.yml not writable

### ISSUE THREAD

**Issue by robertoperuzzo** [lucacracco/robo-drupal#3]
I was wondering why don't we change permissions to `chmod 444` of these two files at the end of the scaffold command.

https://github.com/lucacracco/robo-drupal/blob/0933d883f1be90fe99531333d4ff89004cd76341/src/Task/Drupal/Drupal8Task.php#L292

<img width="1246" alt="Screenshot 2021-12-28 at 16 10 06" src="https://user-images.githubusercontent.com/6221210/147580038-744f5e84-3ea6-4d66-856f-157660a4cf06.png">

**Comment by lucacracco** [comment]
The tool was born for development scope. The file permissions settings were just annoying.

If you want to set the correct permission of these files you can do it by attach this in pre/post command "scaffold".
See https://github.com/lucacracco/robo-drupal/blob/0933d883f1be90fe99531333d4ff89004cd76341/src/RoboFileExample.php#L18

If you want to propose a modify you can, I await a PR ;)
