### ISSUE TITLE
Missing --uri option in deploy command on multisite

### ISSUE THREAD

**Issue by robertoperuzzo** [lucacracco/robo-drupal#5]
Release: 3.0.0

If I run `robo config:import -s my-site` the config-import Drush command add correctly the option `--uri=my-site`, but when I run `robo deploy -s my-site` no option `--uri=my-site` is added to all the Drush commands.

**Comment by lucacracco** [comment]
@robertoperuzzo try https://github.com/lucacracco/robo-drupal/releases/tag/v3.0.1

**Comment by robertoperuzzo** [comment]
@lucacracco it works fine. I close this issue.
